### PR TITLE
Fix RequestTakeoff command

### LINKED ISSUE #56: Problems in RequestTakeoff
Tests over #50 after merging with develop still present problem in commands execution. Current logs reported an issue in the arm->takeoff sequence by not storing current armed state when using QGC takeoff operation.

Logs shows a successful initialization with the unexpected behavior after triggering the takeoff operation as shown next:
```plain
2026-04-13 21:03:17.318 10872-11387 MAVLinkController       org.WenuLink                         I  (DefaultDispatcher-worker-18:459) Service is up an ready
2026-04-13 21:03:17.319 10872-11387 MAVLinkService          org.WenuLink                         D  (DefaultDispatcher-worker-18:459) MAVLinkService (ready?=true) (GCS?=true) (listening?=true) (sending=true)
2026-04-13 21:03:17.537 10872-11350 MAVLinkController       org.WenuLink                         D  (DefaultDispatcher-worker-1:431) Processing message: MAVLINK_MSG_ID_REQUEST_DATA_STREAM
2026-04-13 21:03:18.103 10872-11350 MAVLinkController       org.WenuLink                         D  (DefaultDispatcher-worker-1:431) Processing message: MAVLINK_MSG_ID_REQUEST_DATA_STREAM
2026-04-13 21:03:18.152 10872-11350 MAVLinkController       org.WenuLink                         D  (DefaultDispatcher-worker-1:431) Processing message: MAVLINK_MSG_ID_COMMAND_LONG
2026-04-13 21:03:18.152 10872-11350 MAVLinkController       org.WenuLink                         D  (DefaultDispatcher-worker-1:431) 	- COMMAND_LONG ID: 512
2026-04-13 21:03:18.153 10872-11350 MAVLinkController       org.WenuLink                         D  (DefaultDispatcher-worker-1:431) 	- REQUEST_LONG ID: 280
...
2026-04-13 21:03:34.537 10872-11350 MAVLinkController       org.WenuLink                         D  (DefaultDispatcher-worker-1:431) Processing message: MAVLINK_MSG_ID_REQUEST_DATA_STREAM
2026-04-13 21:03:35.097 10872-11350 MAVLinkController       org.WenuLink                         D  (DefaultDispatcher-worker-1:431) Processing message: MAVLINK_MSG_ID_REQUEST_DATA_STREAM
2026-04-13 21:03:35.503 10872-11350 MAVLinkController       org.WenuLink                         D  (DefaultDispatcher-worker-1:431) Processing message: MAVLINK_MSG_ID_COMMAND_LONG
2026-04-13 21:03:35.503 10872-11350 MAVLinkController       org.WenuLink                         D  (DefaultDispatcher-worker-1:431) 	- COMMAND_LONG ID: 511
2026-04-13 21:03:35.507 10872-11350 MAVLinkController       org.WenuLink                         D  (DefaultDispatcher-worker-1:431) Processing message: MAVLINK_MSG_ID_COMMAND_LONG
2026-04-13 21:03:35.507 10872-11350 MAVLinkController       org.WenuLink                         D  (DefaultDispatcher-worker-1:431) 	- COMMAND_LONG ID: 511
2026-04-13 21:03:35.536 10872-11350 MAVLinkController       org.WenuLink                         D  (DefaultDispatcher-worker-1:431) Processing message: MAVLINK_MSG_ID_REQUEST_DATA_STREAM
2026-04-13 21:03:36.098 10872-11350 MAVLinkController       org.WenuLink                         D  (DefaultDispatcher-worker-1:431) Processing message: MAVLINK_MSG_ID_REQUEST_DATA_STREAM
2026-04-13 21:03:36.537 10872-11350 MAVLinkController       org.WenuLink                         D  (DefaultDispatcher-worker-1:431) Processing message: MAVLINK_MSG_ID_REQUEST_DATA_STREAM
2026-04-13 21:03:37.101 10872-11350 MAVLinkController       org.WenuLink                         D  (DefaultDispatcher-worker-1:431) Processing message: MAVLINK_MSG_ID_REQUEST_DATA_STREAM
2026-04-13 21:03:37.536 10872-11350 MAVLinkController       org.WenuLink                         D  (DefaultDispatcher-worker-1:431) Processing message: MAVLINK_MSG_ID_REQUEST_DATA_STREAM
2026-04-13 21:03:38.100 10872-11350 MAVLinkController       org.WenuLink                         D  (DefaultDispatcher-worker-1:431) Processing message: MAVLINK_MSG_ID_REQUEST_DATA_STREAM
2026-04-13 21:03:38.187 10872-11350 MAVLinkController       org.WenuLink                         D  (DefaultDispatcher-worker-1:431) Processing message: MAVLINK_MSG_ID_COMMAND_LONG
2026-04-13 21:03:38.188 10872-11350 MAVLinkController       org.WenuLink                         D  (DefaultDispatcher-worker-1:431) 	- COMMAND_LONG ID: 176
2026-04-13 21:03:38.188 10872-11350 CommandController       org.WenuLink                         D  (DefaultDispatcher-worker-1:431) FlightMode requested: 4
2026-04-13 21:03:38.190 10872-11350 AircraftHandler         org.WenuLink                         D  (DefaultDispatcher-worker-1:431) Mode change: STABILIZE -> GUIDED
2026-04-13 21:03:38.598 10872-11350 MAVLinkController       org.WenuLink                         D  (DefaultDispatcher-worker-1:431) Processing message: MAVLINK_MSG_ID_REQUEST_DATA_STREAM
2026-04-13 21:03:39.176 10872-11350 MAVLinkController       org.WenuLink                         D  (DefaultDispatcher-worker-1:431) Processing message: MAVLINK_MSG_ID_REQUEST_DATA_STREAM
2026-04-13 21:03:39.279 10872-11350 MAVLinkController       org.WenuLink                         D  (DefaultDispatcher-worker-1:431) Processing message: MAVLINK_MSG_ID_COMMAND_LONG
2026-04-13 21:03:39.279 10872-11350 MAVLinkController       org.WenuLink                         D  (DefaultDispatcher-worker-1:431) 	- COMMAND_LONG ID: 400
2026-04-13 21:03:39.279 10872-11350 CommandController       org.WenuLink                         D  (DefaultDispatcher-worker-1:431) Requesting to arm motors
2026-04-13 21:03:39.282 10872-10872 AircraftHandler         org.WenuLink                         D  (main:2) Executing: ArmCommand
2026-04-13 21:03:39.284 10872-10872 CommandController       org.WenuLink                         D  (main:2) processTakeoff: Success(value=kotlin.Unit)
2026-04-13 21:03:39.300 10872-10872 AircraftHandler         org.WenuLink                         W  (main:2) State reconciliation: AircraftState(mavlink=4, landed=1, homeCoordinates=null, modeFlag=153, flightMode=GUIDED) -> AircraftState(mavlink=3, landed=1, homeCoordinates=null, modeFlag=153, flightMode=GUIDED)
2026-04-13 21:03:39.586 10872-11350 MAVLinkController       org.WenuLink                         D  (DefaultDispatcher-worker-1:431) Processing message: MAVLINK_MSG_ID_REQUEST_DATA_STREAM
2026-04-13 21:03:40.158 10872-11350 MAVLinkController       org.WenuLink                         D  (DefaultDispatcher-worker-1:431) Processing message: MAVLINK_MSG_ID_REQUEST_DATA_STREAM
2026-04-13 21:03:40.262 10872-11350 MAVLinkController       org.WenuLink                         D  (DefaultDispatcher-worker-1:431) Processing message: MAVLINK_MSG_ID_COMMAND_LONG
2026-04-13 21:03:40.263 10872-11350 MAVLinkController       org.WenuLink                         D  (DefaultDispatcher-worker-1:431) 	- COMMAND_LONG ID: 22
2026-04-13 21:03:40.264 10872-11350 CommandController       org.WenuLink                         D  (DefaultDispatcher-worker-1:431) processTakeoff: MAVLINK_MSG_ID_COMMAND_LONG - sysid:255 compid:190 param1:0.0 param2:0.0 param3:0.0 param4:0.0 param5:0.0 param6:0.0 param7:19.9 command:22 target_system:1 target_component:1 confirmation:0
2026-04-13 21:03:40.268 10872-10872 WenuLinkHandler         org.WenuLink                         D  (main:2) Executing: RequestTakeoff
2026-04-13 21:03:40.269 10872-10872 CommandController       org.WenuLink                         D  (main:2) processTakeoff: Failure(reason=Not armed)
2026-04-13 21:03:40.538 10872-11350 MAVLinkController       org.WenuLink                         D  (DefaultDispatcher-worker-1:431) Processing message: MAVLINK_MSG_ID_REQUEST_DATA_STREAM
2026-04-13 21:03:41.113 10872-11350 MAVLinkController       org.WenuLink                         D  (DefaultDispatcher-worker-1:431) Processing message: MAVLINK_MSG_ID_REQUEST_DATA_STREAM
2026-04-13 21:03:41.537 10872-11350 MAVLinkController       org.WenuLink                         D  (DefaultDispatcher-worker-1:431) Processing message: MAVLINK_MSG_ID_REQUEST_DATA_STREAM
2026-04-13 21:03:42.104 10872-11350 MAVLinkController       org.WenuLink                         D  (DefaultDispatcher-worker-1:431) Processing message: MAVLINK_MSG_ID_REQUEST_DATA_STREAM
```

### PR DESCRIPTION
**Pull request by angel-ayala**
These changes updated the aircraft state transition to correctly advance from boot to isFlying, some validations and restriction were intentionally leave out, since there were not enough reasons to have it considering special flightmode cases

Fixes #56 and `SetHomePositionCommand` with a more adequate logic

### CODE REVIEW

**Comment by angel-ayala** [comment]
Just to mention that something else needs to be done, the `RequestTakeoff` command now is being executed without errors, but it does not update its state correctly and is not increasing its altitude during the `RepositionAction`. The test was done using QGC with the takeoff button, and after command execution was not reflected into the QGC UI that such action was done, still being enabled the takeoff button.
Additionally, still needs to incorporate the recent ready-to-merge PR updates.

**Comment by angel-ayala** [comment]
All seems to be addressed, I will merge with latest develop stage.

**Comment by angel-ayala** [comment]
More tests were done and now seems to be working fine, iterative takeoff and landing were successful with the simulation feature. Remaining commands need to be checked, for example `RepositionAction` is doing nothing, ending right after execution started.

File: app/src/main/java/org/WenuLink/adapters/aircraft/AircraftState.kt [hunk 1]
```diff
@@ -200,6 +201,7 @@ data class FlightModeTransition(private val flightMode: ArduCopterFlightMode) :
     }
 
     override fun reduce(from: AircraftState): AircraftState = from.copy(
+        landed = MAV_LANDED_STATE.MAV_LANDED_STATE_IN_AIR,
```
Comment (TimonSchreiber) [inline app/src/main/java/org/WenuLink/adapters/aircraft/AircraftState.kt]:
```suggestion
```

File: app/src/main/java/org/WenuLink/adapters/aircraft/AircraftHandler.kt [hunk 2]
```diff
@@ -141,16 +147,17 @@ class AircraftHandler : CommandHandler<AircraftHandler>() {
...
+        stateMachine.updateHomePosition(it)
+        true
+    } ?: run {
         // Ask for home position
         logger.d { "Requesting home coordinates update with current aircraft's location." }
         FCManager.setHomePosition { error ->
-            if (error != null) {
-                logger.w { "Error request: $error" }
-            }
+            logger.d { "Error in set home position: $error" }
```
Comment (TimonSchreiber) [inline app/src/main/java/org/WenuLink/adapters/aircraft/AircraftHandler.kt]:
```suggestion
            if (error != null) {
                logger.w { "Error in set home position: $error" }
            }
```

File: app/src/main/java/org/WenuLink/adapters/aircraft/AircraftHandler.kt [hunk 3]
```diff
@@ -211,36 +220,47 @@ class AircraftHandler : CommandHandler<AircraftHandler>() {
 
     fun armMotors() {
         logger.d { "Arming motors" }
-        FCManager.armMotors()
+        FCManager.armMotors { error ->
+            logger.d { "Arm error: $error" }
```
Comment (TimonSchreiber) [inline app/src/main/java/org/WenuLink/adapters/aircraft/AircraftHandler.kt]:
```suggestion
            if (error != null) {
                logger.w { "Arm error: $error" }
            }
```

File: app/src/main/java/org/WenuLink/adapters/aircraft/AircraftHandler.kt [hunk 4]
```diff
@@ -211,36 +220,47 @@ class AircraftHandler : CommandHandler<AircraftHandler>() {
...
+        }
     }
 
     fun disarmMotors() {
         logger.d { "Disarming motors" }
-        FCManager.disarmMotors()
+        FCManager.disarmMotors { error ->
+            logger.d { "Disarm error: $error" }
```
Comment (TimonSchreiber) [inline app/src/main/java/org/WenuLink/adapters/aircraft/AircraftHandler.kt]:
```suggestion
            if (error != null) {
                logger.w { "Disarm error: $error" }
            }
```

File: app/src/main/java/org/WenuLink/adapters/aircraft/AircraftHandler.kt [hunk 5]
```diff
@@ -211,36 +220,47 @@ class AircraftHandler : CommandHandler<AircraftHandler>() {
...
+        syncState()
+
         return motorsUpdated
     }
 
     fun takeOff() {
         logger.d { "Aircraft taking off" }
-        FCManager.startTakeoff()
+        FCManager.startTakeoff { error ->
+            logger.d { "Takeoff error: $error" }
```
Comment (TimonSchreiber) [inline app/src/main/java/org/WenuLink/adapters/aircraft/AircraftHandler.kt]:
```suggestion
            if (error != null) {
                logger.w { "Takeoff error: $error" }
            }
```

File: app/src/main/java/org/WenuLink/sdk/MissionActionManager.kt [hunk 6]
```diff
@@ -57,27 +57,26 @@ object MissionActionManager {
         return key
     }
 
-    fun onFinish(action: KClass<out TimelineElement>, callback: () -> Unit) =
+    fun onFinish(action: KClass<out TimelineElement>, callback: () -> Unit): ActionCallbackKey =
         registerCallback(action, TimelineEvent.FINISHED, callback)
 
     fun startListener(onError: (String) -> Unit = {}) {
```
Comment (TimonSchreiber) [inline app/src/main/java/org/WenuLink/sdk/MissionActionManager.kt:63]: Was there a reason to remove this?
```suggestion
    fun startListener(onError: (String) -> Unit = {}) {
        stopListener()
```

**Review by TimonSchreiber — CHANGES_REQUESTED** [review]
#### 1. `checkTransition` is a tautology
`AircraftStateMachine.dispatch` sets `this.transition = event` unconditionally, and `isStateTransition(target)` just returns `transition == target`. So in `RequestTransition.execute`:

```kotlin
ctx.aircraft.dispatchTransition(transition)
return if (ctx.aircraft.checkTransition(transition)) {
    CommandResult.ok
} else {
    CommandResult.error("Unsuccessful state transition")
}
```

the erro branch is unreachable, every `RequestTransition` succeeds at this step regardless of what `reduce` actually did. The old `prevState != state` check wasn't perfect but was at least observable. What's the intended semantics here? If it's "did the dispatch stick", comparing against `event.reduce(prev)` would be more meaningful; if it's "is the dispatch valid", `validate()` already covers that pre-execute and this check is redundant.

---

#### 2. `FlightModeTransition.reduce` forces `landed = IN_AIR` unconditionally
My guess for "state not updating" after takeoff. QGC's flow starts with `SET_MODE(GUIDED)` on the ground; after the new reduce, `landed` becomes `IN_AIR` while the drone is still on the pad. `resolveFrom` can then no longer recover:
- `!isArmed && isOnTheGround()` --> false (landed isn't `ON_GROUND`)
- `isArmed && isOnTheGround()` --> false
- both `isLanding()` branches --> false
- `isFlying` --> false
- falls through to `else -> this.landed` --> stuck at `IN_AIR`

I would expect this also explains why QGC keeps the takeoff button enabled.

---

And I would change the log level of the errors to warning as well as adding the guards back.

Is there a reason to remove `stopListener` from `MissionActionManager.startListener`?

**Comment by angel-ayala** [comment]
Regards to your first point, you are correct in pointing it as a tautology, I was unsure if leave it out or no, since makes sense to perform some pre process for `RequestTransition`. Previous version was checking the state object with a direct comparison `==` but if in a certain state was not armed, and then transitioned to armed, error has been arising because this continuous sync. So to compare if the state was transitioned or no I leave it that way.
Nevertheless, as you mentioned `validate()` already covers a pre-execution verification and now seems to be redundant. Originally was to check if "did the dispatch stick", but as I mentioned the application layer must always updating the flightmode and state changes to react accordingly, as we have done with hooks method. Hence, handler  update all that is necessary through events and listeners as they arrive, while the related MAVLink flags update must be triggered only in specific situations, as the case of taking off and landing. I will update it accordingly

Good catch in 2, I though that was the FlightTransition but no, my bad.
Regards to the `stopListener()` I just removed from start listeners to have separate concerns and intentions, in addition to being called twice, in the same function. The overall idea in `MissionActionManager` is to clear both schedule and listeners first, to then schedule the next action, set the listeners, and starts the execution, for the next action repeated and all new arriving action have a clear schedule for its

**Comment by angel-ayala** [comment]
I ran out the same tests again and when reached the `RepositionAction` it doesn't did anything, so I stopped everything and at the end it showed up an error during the `TimelineMission`. My first thought is that something related to threading, requiring to move the listener to main scope, from the following log lines, at the end there is a `(timeline thread:xxx)` showing up such error when according to such logic should be pop out earlier.

```plain
2026-04-18 13:53:46.040  9982-10611 MAVLinkController       org.WenuLink                         D  (DefaultDispatcher-worker-2:456) Processing message: MAVLINK_MSG_ID_REQUEST_DATA_STREAM
2026-04-18 13:53:46.440  9982-10611 MAVLinkController       org.WenuLink                         D  (DefaultDispatcher-worker-2:456) Processing message: MAVLINK_MSG_ID_COMMAND_LONG
2026-04-18 13:53:46.441  9982-10611 MAVLinkController       org.WenuLink                         D  (DefaultDispatcher-worker-2:456) 	- COMMAND_LONG ID: 176
2026-04-18 13:53:46.442  9982-10611 CommandController       org.WenuLink                         D  (DefaultDispatcher-worker-2:456) FlightMode requested: GUIDED
2026-04-18 13:53:46.444  9982-10611 AircraftHandler         org.WenuLink                         D  (DefaultDispatcher-worker-2:456) Mode change: STABILIZE -> GUIDED
2026-04-18 13:53:46.604  9982-10611 MAVLinkController       org.WenuLink                         D  (DefaultDispatcher-worker-2:456) Processing message: MAVLINK_MSG_ID_REQUEST_DATA_STREAM
2026-04-18 13:53:46.817  9982-10611 MAVLinkController       org.WenuLink                         D  (DefaultDispatcher-worker-2:456) Processing message: MAVLINK_MSG_ID_COMMAND_LONG
2026-04-18 13:53:46.818  9982-10611 MAVLinkController       org.WenuLink                         D  (DefaultDispatcher-worker-2:456) 	- COMMAND_LONG ID: 400
2026-04-18 13:53:46.819  9982-10611 CommandController       org.WenuLink                         D  (DefaultDispatcher-worker-2:456) Requesting to arm motors
2026-04-18 13:53:46.822  9982-9982  AircraftHandler         org.WenuLink                         D  (main:2) Executing: ArmCommand
2026-04-18 13:53:46.825  9982-9982  AircraftHandler         org.WenuLink                         D  (main:2) Command ended: ArmCommand
2026-04-18 13:53:47.128  9982-10611 MAVLinkController       org.WenuLink                         D  (DefaultDispatcher-worker-2:456) Processing message: MAVLINK_MSG_ID_REQUEST_DATA_STREAM
2026-04-18 13:53:47.703  9982-10611 MAVLinkController       org.WenuLink                         D  (DefaultDispatcher-worker-2:456) Processing message: MAVLINK_MSG_ID_REQUEST_DATA_STREAM
2026-04-18 13:53:47.807  9982-10611 MAVLinkController       org.WenuLink                         D  (DefaultDispatcher-worker-2:456) Processing message: MAVLINK_MSG_ID_COMMAND_LONG
2026-04-18 13:53:47.808  9982-10611 MAVLinkController       org.WenuLink                         D  (DefaultDispatcher-worker-2:456) 	- COMMAND_LONG ID: 22
2026-04-18 13:53:47.808  9982-10611 CommandController       org.WenuLink                         D  (DefaultDispatcher-worker-2:456) processTakeoff: MAVLINK_MSG_ID_COMMAND_LONG - sysid:255 compid:190 param1:0.0 param2:0.0 param3:0.0 param4:0.0 param5:0.0 param6:0.0 param7:10.4 command:22 target_system:1 target_component:1 confirmation:0
2026-04-18 13:53:47.812  9982-9982  WenuLinkHandler         org.WenuLink                         D  (main:2) Executing: RequestTakeoff
2026-04-18 13:53:47.816  9982-9982  AircraftHandler         org.WenuLink                         D  (main:2) Executing: SetHomePositionCommand
2026-04-18 13:53:47.819  9982-9982  AircraftHandler         org.WenuLink                         D  (main:2) Home coordinates acquired: Coordinates3D(lat=-8.066478642777481, long=-34.98744367551871, alt=60.0).
2026-04-18 13:53:47.820  9982-9982  AircraftHandler         org.WenuLink                         D  (main:2) Home coordinates acquired: Coordinates3D(lat=-8.066478642777481, long=-34.98744367551871, alt=60.0).
2026-04-18 13:53:47.821  9982-9982  AircraftHandler         org.WenuLink                         D  (main:2) Command ended: SetHomePositionCommand
2026-04-18 13:53:47.824  9982-9982  AircraftHandler         org.WenuLink                         D  (main:2) Executing: TakeoffCommand
2026-04-18 13:53:47.826  9982-9982  AircraftHandler         org.WenuLink                         D  (main:2) Aircraft taking off
2026-04-18 13:53:47.833  9982-9982  AircraftHandler         org.WenuLink                         D  (main:2) Waiting for taking off
2026-04-18 13:53:48.040  9982-10611 MAVLinkController       org.WenuLink                         D  (DefaultDispatcher-worker-2:456) Processing message: MAVLINK_MSG_ID_REQUEST_DATA_STREAM
2026-04-18 13:53:48.189  9982-10359 ContextImpl             org.WenuLink                         W  Failed to ensure /storage/753C-AA2D/Android/data/org.WenuLink/files/DJI: android.os.ServiceSpecificException:  (code -30)
2026-04-18 13:53:48.612  9982-10611 MAVLinkController       org.WenuLink                         D  (DefaultDispatcher-worker-2:456) Processing message: MAVLINK_MSG_ID_REQUEST_DATA_STREAM
...
2026-04-18 13:53:50.611  9982-10611 MAVLinkController       org.WenuLink                         D  (DefaultDispatcher-worker-2:456) Processing message: MAVLINK_MSG_ID_REQUEST_DATA_STREAM
2026-04-18 13:53:50.863  9982-9982  AircraftHandler         org.WenuLink                         I  (main:2) Aircraft flying
2026-04-18 13:53:50.864  9982-9982  AircraftHandler         org.WenuLink                         I  (main:2) New aircraft state: AircraftState(mavlink=4, landed=2, homeCoordinates=Coordinates3D(lat=-8.066478642777481, long=-34.98744367551871, alt=60.0), modeFlag=153, flightMode=GUIDED)
2026-04-18 13:53:50.869  9982-9982  AircraftHandler         org.WenuLink                         D  (main:2) Command ended: TakeoffCommand
2026-04-18 13:53:50.880  9982-9982  MissionHandler          org.WenuLink                         D  (main:2) Executing: RepositionAction
2026-04-18 13:53:50.892  9982-10730 MissionActionManager    org.WenuLink                         D  (timeline thread:537) Timeline event: STARTED
2026-04-18 13:53:50.894  9982-10404 MissionActionManager    org.WenuLink                         D  (RxComputationThreadPool-5:232) Timeline event: STARTED
2026-04-18 13:53:51.040  9982-10611 MAVLinkController       org.WenuLink                         D  (DefaultDispatcher-worker-2:456) Processing message: MAVLINK_MSG_ID_REQUEST_DATA_STREAM
2026-04-18 13:53:51.601  9982-10611 MAVLinkController       org.WenuLink                         D  (DefaultDispatcher-worker-2:456) Processing message: MAVLINK_MSG_ID_REQUEST_DATA_STREAM
2026-04-18 13:53:51.730  9982-10611 MAVLinkController       org.WenuLink                         D  (DefaultDispatcher-worker-2:456) Processing message: MAVLINK_MSG_ID_COMMAND_LONG
2026-04-18 13:53:51.730  9982-10611 MAVLinkController       org.WenuLink                         D  (DefaultDispatcher-worker-2:456) 	- COMMAND_LONG ID: 511
2026-04-18 13:53:51.731  9982-10611 TelemetryController     org.WenuLink                         D  (DefaultDispatcher-worker-2:456) processMessageInterval
2026-04-18 13:53:51.735  9982-10611 MAVLinkController       org.WenuLink                         D  (DefaultDispatcher-worker-2:456) Processing message: MAVLINK_MSG_ID_COMMAND_LONG
2026-04-18 13:53:51.736  9982-10611 MAVLinkController       org.WenuLink                         D  (DefaultDispatcher-worker-2:456) 	- COMMAND_LONG ID: 511
2026-04-18 13:53:51.736  9982-10611 TelemetryController     org.WenuLink                         D  (DefaultDispatcher-worker-2:456) processMessageInterval
2026-04-18 13:53:52.039  9982-10611 MAVLinkController       org.WenuLink                         D  (DefaultDispatcher-worker-2:456) Processing message: MAVLINK_MSG_ID_REQUEST_DATA_STREAM
...
2026-04-18 13:54:28.600  9982-10611 MAVLinkController       org.WenuLink                         D  (DefaultDispatcher-worker-2:456) Processing message: MAVLINK_MSG_ID_REQUEST_DATA_STREAM
2026-04-18 13:54:42.461  9982-9992  org.WenuLink            org.WenuLink                         I  Background young concurrent copying GC freed 19MB AllocSpace bytes, 0(0B) LOS objects, 28% free, 48MB/67MB, paused 663us,484us total 100.255ms
2026-04-18 13:54:57.255  9982-9982  WenuLinkHandler         org.WenuLink                         W  (main:2) Command cancelled: RequestTakeoff
2026-04-18 13:54:57.255  9982-9982  AircraftHandler         org.WenuLink                         D  (main:2) Mode change: GUIDED -> STABILIZE
2026-04-18 13:55:01.310  9982-9992  org.WenuLink            org.WenuLink                         I  Background young concurrent copying GC freed 19MB AllocSpace bytes, 0(0B) LOS objects, 28% free, 48MB/67MB, paused 363us,441us total 103.273ms
2026-04-18 13:55:03.078  9982-10611 MAVLinkController       org.WenuLink                         D  (DefaultDispatcher-worker-2:456) Processing message: MAVLINK_MSG_ID_COMMAND_LONG
2026-04-18 13:55:03.078  9982-10611 MAVLinkController       org.WenuLink                         D  (DefaultDispatcher-worker-2:456) 	- COMMAND_LONG ID: 176
2026-04-18 13:55:03.079  9982-10611 CommandController       org.WenuLink                         D  (DefaultDispatcher-worker-2:456) FlightMode requested: LAND
2026-04-18 13:55:03.080  9982-10611 AircraftHandler         org.WenuLink                         D  (DefaultDispatcher-worker-2:456) Mode change: STABILIZE -> LAND
2026-04-18 13:55:03.095  9982-9982  WenuLinkHandler         org.WenuLink                         D  (main:2) Executing: RequestLand
2026-04-18 13:55:07.463  9982-10359 DJIPackManager          org.WenuLink                         E  pack senderType=3 cmdSet=11
2026-04-18 13:55:20.932  9982-9982  ServicesViewModel       org.WenuLink                         D  (main:2) runService(false)
2026-04-18 13:55:20.932  9982-9982  AircraftHandler         org.WenuLink                         D  (main:2) Mode change: LAND -> STABILIZE
2026-04-18 13:55:20.941  9982-9982  WenuLinkService         org.WenuLink                         I  (main:2) WebRTC service stop.
2026-04-18 13:55:20.942  9982-9982  MAVLinkService          org.WenuLink                         D  (main:2) Requesting to stop MAVLinkService.
2026-04-18 13:55:20.943  9982-10615 MAVLinkService          org.WenuLink                         D  (DefaultDispatcher-worker-6:460) Stop client listening
2026-04-18 13:55:20.943  9982-9982  MAVLinkService          org.WenuLink                         D  (main:2) Waiting 5s for client to stop
2026-04-18 13:55:20.943  9982-10615 MAVLinkService          org.WenuLink                         D  (DefaultDispatcher-worker-6:460) Stop client sending
2026-04-18 13:55:20.944  9982-10615 MAVLinkClient           org.WenuLink                         D  (DefaultDispatcher-worker-6:460) Sending end
2026-04-18 13:55:20.944  9982-10611 MAVLinkClient           org.WenuLink                         D  (DefaultDispatcher-worker-2:456) Listening end
2026-04-18 13:55:20.947  9982-9982  WenuLinkHandler         org.WenuLink                         W  (main:2) Command cancelled: RequestLand
2026-04-18 13:55:21.445  9982-9982  MAVLinkService          org.WenuLink                         D  (main:2) MAVLinkClient ended.
2026-04-18 13:55:21.446  9982-9982  WenuLinkService         org.WenuLink                         I  (main:2) MAVLinkService stop: true
2026-04-18 13:55:21.455  9982-9982  WenuLinkService         org.WenuLink                         I  (main:2) WenuLinkService ended
2026-04-18 13:55:24.557  9982-9982  WenuLinkHandler         org.WenuLink                         D  (main:2) Stop monitor job
2026-04-18 13:55:24.559  9982-9982  MissionHandler          org.WenuLink                         W  (main:2) Command cancelled: RepositionAction
2026-04-18 13:55:24.559  9982-9982  MissionHandler          org.WenuLink                         D  (main:2) Executing: LandAction
2026-04-18 13:55:24.559  9982-9982  AircraftHandler         org.WenuLink                         D  (main:2) Executing: ShutdownCommand
2026-04-18 13:55:24.560  9982-9982  WenuLinkHandler         org.WenuLink                         W  (main:2) Monitor loop CancellationException
2026-04-18 13:55:24.561  9982-9982  TelemetryHandler        org.WenuLink                         D  (main:2) Requesting to stop telemetry broadcast.
2026-04-18 13:55:24.562  9982-9982  TelemetryHandler        org.WenuLink                         D  (main:2) registerStateListeners: false (runSimulation: true)
2026-04-18 13:55:24.562  9982-9982  RCManager               org.WenuLink                         D  (main:2) Stopping RC BatteryListener
2026-04-18 13:55:24.562  9982-9982  RCManager               org.WenuLink                         D  (main:2) Stoping RC HardwareListener
2026-04-18 13:55:24.564  9982-9982  SimManager              org.WenuLink                         D  (main:2) Simulation stop.
2026-04-18 13:55:24.567  9982-10730 MissionActionManager    org.WenuLink                         D  (timeline thread:537) Timeline event: STOP_ERROR
2026-04-18 13:55:24.567  9982-10730 MissionActionManager    org.WenuLink                         D  (timeline thread:537) Timeline error: The command is not supported in current state.
2026-04-18 13:55:24.569  9982-10730 MissionActionManager    org.WenuLink                         D  (timeline thread:537) Timeline event: STOPPED
2026-04-18 13:55:25.061  9982-9982  TelemetryHandler        org.WenuLink                         D  (main:2) Telemetry stop: true
2026-04-18 13:55:25.063  9982-9982  AircraftHandler         org.WenuLink                         D  (main:2) Command ended: ShutdownCommand
2026-04-18 13:55:25.065  9982-9982  TelemetryHandler        org.WenuLink                         W  (main:2) Deactivating the simulation requires to reboot the Aircraft for real aircraft connection
2026-04-18 13:55:25.065  9982-9982  TelemetryHandler        org.WenuLink                         I  (main:2) Enable Simulation false
2026-04-18 13:55:25.191  9982-9982  FileUtils               org.WenuLink                         E  err write to mi_exception_log
2026-04-18 13:55:25.877  9982-9982  TelemetryHandler        org.WenuLink                         I  (main:2) Simulation stopped.
2026-04-18 13:55:26.369  9982-10592 FileUtils               org.WenuLink                         E  err open mi_exception_log errno=2
2026-04-18 13:55:26.369  9982-10592 FileUtils               org.WenuLink                         E  err write to mi_exception_log
2026-04-18 13:55:27.230  9982-9992  org.WenuLink            org.WenuLink                         I  Background young concurrent copying GC freed 10MB AllocSpace bytes, 5(468KB) LOS objects, 0% free, 68MB/68MB, paused 422us,63us total 236.404ms
2026-04-18 13:55:27.472  9982-9992  org.WenuLink            org.WenuLink                         I  Background concurrent copying GC freed 5686KB AllocSpace bytes, 0(0B) LOS objects, 26% free, 66MB/90MB, paused 77us,154us total 240.752ms
2026-04-18 13:55:27.605  9982-10592 FileUtils               org.WenuLink                         E  err open mi_exception_log errno=2
2026-04-18 13:55:27.605  9982-10592 FileUtils               org.WenuLink                         E  err write to mi_exception_log
```

**Review by TimonSchreiber — APPROVED** [review]
Great work @angel-ayala
