### PR TITLE
Fix CameraController for proper handling of different camera id device

### LINKED ISSUE #84: [Bug]: Camera not found in P4P
### WenuLink App Version

ae1d862

### Drone Model

Phantom 4 Pro

### Test Environment

DJI Simulator

### Android Device (running WenuLink)

Xiaomi Redmi Note 10s

### Android Version

Android 13

### Remote Controller (if separate)

GL300F

### GCS Software & Version

QGroundControl v5.0.8 64 bit

### Related MAVLink Microservice

- [ ] Heartbeat/Connection
- [ ] Mission
- [ ] Parameter
- [x] Command
- [x] Camera
- [ ] Other (describe below)

### Related MAVLink Message(s)

_No response_

### Steps to Reproduce

1. Launch app
2. Connect the drone using the simulation feature
3. Start services
4. Use the record button on QGC under the photo mode

### Reproducibility

Always

### Expected Behavior

Print something related to the photo shoot

### Actual Behavior

Nothing, log says that no camera was found

### Logs

```plain
2026-04-21 15:25:14.109 10300-10617 MAVLinkController       org.WenuLink                         D  (DefaultDispatcher-worker-1:360) Processing message: MAVLINK_MSG_ID_REQUEST_DATA_STREAM
2026-04-21 15:25:14.544 10300-10617 MAVLinkController       org.WenuLink                         D  (DefaultDispatcher-worker-1:360) Processing message: MAVLINK_MSG_ID_REQUEST_DATA_STREAM
2026-04-21 15:25:15.103 10300-10617 MAVLinkController       org.WenuLink                         D  (DefaultDispatcher-worker-1:360) Processing message: MAVLINK_MSG_ID_REQUEST_DATA_STREAM
2026-04-21 15:25:15.106 10300-10617 MAVLinkController       org.WenuLink                         D  (DefaultDispatcher-worker-1:360) Processing message: MAVLINK_MSG_ID_COMMAND_LONG
2026-04-21 15:25:15.107 10300-10617 MAVLinkController       org.WenuLink                         D  (DefaultDispatcher-worker-1:360) 	- COMMAND_LONG ID: 2000
2026-04-21 15:25:15.108 10300-10617 CameraController        org.WenuLink                         D  (DefaultDispatcher-worker-1:360) Camera index 0 not found
```

### Additional Notes

I will run a test connecting to the real hardware listeners to check if is not something related to the simulation feature. Nevertheless, the only thing that should be affecting is the `FlightController` and not other components I guess. On the opposite, something else is causing this.

### PR DESCRIPTION
**Pull request by angel-ayala**
Command message related to camera action triggered from QGC always send the camera device id equals to 0, requesting to perform the action for all camera devices present, which was not properly handled.

Fixes #84 by iterating over a list of cameras according to the camera device id argument from message and enhance command definition by clarifying the argument to be id instead of index.

### CODE REVIEW

File: app/src/main/java/org/WenuLink/adapters/camera/CameraHandler.kt [hunk 1]
```diff
@@ -108,57 +115,68 @@ class CameraHandler : CommandHandler<CameraHandler>() {
...
 
-    fun isVideoMode(cameraIdx: Int = 0): Boolean = checkCameraMode(
+    fun isVideoMode(cameraId: Int): Boolean = checkCameraMode(
         CAMERA_MODE.CAMERA_MODE_VIDEO,
-        cameraIdx
+        cameraId
     )
 
-    fun canRecordVideo(cameraIdx: Int = 0): Boolean = CameraManager.canRecordVideo()
+    fun canPhotoInVideo(cameraId: Int): Boolean = CameraManager.canTakePhotoInVideo()
```
Comment (TimonSchreiber) [inline app/src/main/java/org/WenuLink/adapters/camera/CameraHandler.kt]:
```suggestion
    fun canTakePhotoInVideo(cameraId: Int): Boolean = CameraManager.canTakePhotoInVideo()
```

File: app/src/main/java/org/WenuLink/adapters/camera/CameraCommands.kt [hunk 2]
```diff
@@ -42,70 +42,69 @@ data class SetModeCommand(val newMode: Int, val cameraIdx: Int) : CameraCommand
...
         return setModeResult
     }
 }
 
-data class TakePhotoCommand(val cameraIdx: Int) : CameraCommand {
+data class TakePhotoCommand(val cameraId: Int) : CameraCommand {
     override fun validate(ctx: CameraHandler): UnitResult = when {
-        !ctx.isPhotoMode(cameraIdx) -> CommandResult.error("Not in photo mode!")
-        !ctx.captureIdle(cameraIdx) -> CommandResult.error("Busy")
+        ctx.isVideoMode(cameraId) && ctx.canPhotoInVideo(cameraId) -> CommandResult.ok
```
Comment (TimonSchreiber) [inline app/src/main/java/org/WenuLink/adapters/camera/CameraCommands.kt]:
```suggestion
        ctx.isVideoMode(cameraId) && ctx.canTakePhotoInVideo(cameraId) -> CommandResult.ok
```

File: app/src/main/java/org/WenuLink/adapters/camera/CameraData.kt [hunk 3]
```diff
@@ -25,8 +25,15 @@ data class CameraState(
...
-)
+    val captureTimestamp: Long = -1,
+    val totalPhotos: Int = 0
+) {
+    val timeMillis: Long get() = if (captureTimestamp != -1L) {
+        System.currentTimeMillis() - captureTimestamp
+    } else {
+        0
+    }
+}
```
Comment (TimonSchreiber) [inline app/src/main/java/org/WenuLink/adapters/camera/CameraData.kt]:
```suggestion
    val captureTimestamp: Long? = null,
    val totalPhotos: Int = 0
) {
    val timeMillis: Long
         get() = captureTimestamp?.let { System.currentTimeMillis() - it } ?: 0
}
```

File: app/src/main/java/org/WenuLink/adapters/camera/CameraHandler.kt [hunk 4]
```diff
@@ -108,57 +115,68 @@ class CameraHandler : CommandHandler<CameraHandler>() {
...
+
+    fun updateCaptureTimestamp(timestamp: Long, cameraId: Int) =
```
Comment (TimonSchreiber) [inline app/src/main/java/org/WenuLink/adapters/camera/CameraHandler.kt]:
```suggestion
    fun updateCaptureTimestamp(timestamp: Long?, cameraId: Int) =
```

File: app/src/main/java/org/WenuLink/adapters/camera/CameraCommands.kt [hunk 5]
```diff
@@ -115,16 +114,17 @@ data class StopRecordCommand(val cameraIdx: Int) : CameraCommand {
             ?.let { CommandResult.error(it) }
             ?: let {
                 // mark IDLE back
-                ctx.updateCaptureStatus(CameraCaptureStatus.IDLE, cameraIdx)
+                ctx.updateCaptureStatus(CameraCaptureStatus.IDLE, cameraId)
+                ctx.updateCaptureTimestamp(-1, cameraId)
```
Comment (TimonSchreiber) [inline app/src/main/java/org/WenuLink/adapters/camera/CameraCommands.kt]:
```suggestion
                ctx.updateCaptureTimestamp(null, cameraId)
```

File: app/src/main/java/org/WenuLink/adapters/camera/CameraHandler.kt [hunk 6]
```diff
@@ -85,16 +85,23 @@ class CameraHandler : CommandHandler<CameraHandler>() {
                     CAMERA_CAP_FLAGS.CAMERA_CAP_FLAGS_HAS_MODES.toLong()
             )
         )
-        setMode(CAMERA_MODE.CAMERA_MODE_IMAGE, 0)
+        // set mode as a command avoid thread issues
+        dispatchCommand(SetModeCommand(CAMERA_MODE.CAMERA_MODE_IMAGE, 1))
```
Comment (TimonSchreiber) [inline app/src/main/java/org/WenuLink/adapters/camera/CameraHandler.kt]:
```suggestion
        dispatchCommand(SetModeCommand(
            CAMERA_MODE.CAMERA_MODE_IMAGE,
            availableCameras.first().id)
        )
```

**Review by TimonSchreiber — DISMISSED** [review]
Great work @angel-ayala that fixes more than just the camera indexing.

I approved this pr, but left some inline suggestions. Nothing wrong, just personal preferences. Use them or leave them out as you see fit.

---

1. `canPhotoInVideo` to `canTakePhotoInVideo`, so the same name as the layer below and easier to understand (same name for the same thing)
2. Use `null` as unset instead of `-1` for `captureTimestamp`, simplifies the getter
3. Use previously created camera instead of repeating index literal in `dispatchCommand(SetModeCommand(CAMERA_MODE.CAMERA_MODE_IMAGE, 1))` by calling `availableCameras.first().id`

**Comment by angel-ayala** [comment]
Your comments improve the quality of the code, so I applied all of them.

**Review by TimonSchreiber — APPROVED** [review]
Great!
