### PR TITLE
Fix UploadMissionCommand

### LINKED ISSUE #52: Problems with mission uploading
After correcting the init/shutdown sequence in #50 , a bug was encountered when uploading a mission to the P4P using the simulation feature saying `Cannot round Nan value`. More details about when happens in the following log lines:

```plain
2026-04-12 23:24:02.853 14365-14757 NavigationController    org.WenuLink                         D  (DefaultDispatcher-worker-8:344) processMissionItem
2026-04-12 23:24:02.853 14365-14757 NavigationController    org.WenuLink                         D  (DefaultDispatcher-worker-8:344) 	MAVLINK_MSG_ID_MISSION_ITEM_INT - sysid:255 compid:190 param1:0.0 param2:0.0 param3:0.0 param4:0.0 x:0 y:0 z:0.0 seq:6 command:20 target_system:1 target_component:1 frame:2 current:0 autocontinue:1 mission_type:0
2026-04-12 23:24:02.853 14365-14757 MissionHandler          org.WenuLink                         D  (DefaultDispatcher-worker-8:344) Append mission item.
2026-04-12 23:24:02.854 14365-14757 NavigationController    org.WenuLink                         D  (DefaultDispatcher-worker-8:344) ackReceivedItem #6
2026-04-12 23:24:02.856 14365-14365 MissionHandler          org.WenuLink                         D  (main:2) Executing: UploadMissionCommand
2026-04-12 23:24:02.864 14365-14365 MissionHandler          org.WenuLink                         D  (main:2) Command failed: UploadMissionCommand
2026-04-12 23:24:02.864 14365-14365 NavigationController    org.WenuLink                         D  (main:2) sendStatusText
2026-04-12 23:24:03.095 14365-14623 DJIUSBWifiSwitchManager org.WenuLink                         E  ****resetSwitchFromWifiFlag
2026-04-12 23:24:03.098 14365-14623 DJIUsbAccessoryReceiver org.WenuLink                         E  receiver destroySession
--------- beginning of crash
2026-04-12 23:24:03.196 14365-14365 AndroidRuntime          org.WenuLink                         E  FATAL EXCEPTION: main
                                                                                                    Process: org.WenuLink, PID: 14365
                                                                                                    java.lang.IllegalArgumentException: Cannot round NaN value.
                                                                                                    	at kotlin.math.MathKt__MathJVMKt.roundToInt(MathJVM.kt:1165)
                                                                                                    	at org.WenuLink.sdk.MissionManager.mapAction(MissionManager.kt:156)
                                                                                                    	at org.WenuLink.sdk.MissionManager.uploadMission(MissionManager.kt:135)
                                                                                                    	at org.WenuLink.adapters.mission.UploadMissionCommand.execute(MissionCommands.kt:42)
                                                                                                    	at org.WenuLink.adapters.mission.UploadMissionCommand.execute(MissionCommands.kt:31)
                                                                                                    	at org.WenuLink.commands.CommandHandler$startCommandProcessor$1$deferred$1.invokeSuspend(CommandHandler.kt:36)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:211)
                                                                                                    	at android.os.Looper.loop(Looper.java:300)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8232)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
```

By some unexpected reason this suddenly stop to work. I don't remember on any specific change made to coordinates processing, @TimonSchreiber do you have some change in mind that could done this?

### PR DESCRIPTION
**Pull request by angel-ayala**
Changes addressed only focused on update the condition to add a RotateAction or not given recent parameters update

Fixes #52

### CODE REVIEW

**Comment by angel-ayala** [comment]
I just checked, and #79 needs to be merged first

**Comment by angel-ayala** [comment]
I just added some extra changes focusing in the entire mission process, and now is working fine. After this I think is good to report issue and discuss what needs to be done prior to major changes.

File: app/src/main/java/org/WenuLink/adapters/mission/MissionHandler.kt [hunk 1]
```diff
@@ -109,18 +115,25 @@ class MissionHandler : CommandHandler<MissionHandler>() {
         if (!state.unvisitedSequence) return
 
         logger.d { "Processing WP ${state.currentSequence}" }
+        // Wait for AUTO mode on first waypoint
+        if (state.currentSequence == 1) {
+            dispatchCommand(PauseWaypointMission) { result ->
+                logger.d { "PauseWaypoint result: $result" }
```
Comment (TimonSchreiber) [inline app/src/main/java/org/WenuLink/adapters/mission/MissionHandler.kt]:
```suggestion
                if (result.hasError) logger.e { "PauseWaypoint error: ${result.errorReason}" }
```

File: app/src/main/java/org/WenuLink/adapters/RequestCommand.kt [hunk 2]
```diff
@@ -110,13 +111,23 @@ data class RequestStartMission(
...
-
         ctx.dispatchControlAuthority(ControlAuthorityType.WAYPOINT_MISSION)
 
+        // Triggers SDK start function
         ctx.mission.setStartSequence(startSequence)
+        val startResult = ctx.dispatchAndAwait(WenuLinkCommand.Mission(StartWaypointMission))
+        if (startResult.hasError) return startResult
+
+        // Wait initial altitude for mission start (5min top)
+        val initOk = ctx.mission.waitMissionStart(300_000L)
```
Comment (TimonSchreiber) [inline app/src/main/java/org/WenuLink/adapters/RequestCommand.kt:132]: Isn't a 5 minute blocking wait a bit too long? Maybe 30 seconds or 1 minute would be enough
```suggestion
        val initOk = ctx.mission.waitMissionStart(30_000L)
```

File: app/src/main/java/org/WenuLink/adapters/mission/MissionHandler.kt [hunk 3]
```diff
@@ -109,18 +115,25 @@ class MissionHandler : CommandHandler<MissionHandler>() {
...
+        state = state.reset().setStartSequence(sequence)
         return state
     }
 
     @Synchronized
     fun setCurrentSequence(sequence: Int): MissionState {
-        state = state.updateItemSequence(sequence)
+        state = state.updateItemSequence(sequence + 1) // from 0- to 1-index
         if (sequence == -1) state = state.updateItemSequence(null).setComplete().markVisited()
         return state
```
Comment (TimonSchreiber) [inline app/src/main/java/org/WenuLink/adapters/mission/MissionHandler.kt]:
```suggestion
        state = if (sequence == -1) {
            state.updateItemSequence(null).setComplete().markVisited()
        } else {
            state.updateItemSequence(sequence + 1) // from 0- to 1-index
        }
        return state
```

File: app/src/main/java/org/WenuLink/adapters/mission/MissionCommands.kt [hunk 4]
```diff
@@ -152,7 +152,7 @@ data object PauseActionCommand : MissionCommand {
 
 data object ResumeActionCommand : MissionCommand {
     override fun validate(ctx: MissionHandler): UnitResult = when {
-        MissionActionManager.isRunning -> CommandResult.error("Timeline already running")
+        !MissionActionManager.isPaused -> CommandResult.error("Timeline already running")
```
Comment (TimonSchreiber) [inline app/src/main/java/org/WenuLink/adapters/mission/MissionCommands.kt]:
```suggestion
        !MissionActionManager.isPaused -> CommandResult.error("Timeline not paused")
```

File: app/src/main/java/org/WenuLink/adapters/RequestCommand.kt [hunk 5]
```diff
@@ -110,13 +111,23 @@ data class RequestStartMission(
...
+        if (!initOk) return CommandResult.error("Mission did not started!")
```
Comment (TimonSchreiber) [inline app/src/main/java/org/WenuLink/adapters/RequestCommand.kt]:
```suggestion
        if (!initOk) return CommandResult.error("Mission did not start!")
```

File: app/src/main/java/org/WenuLink/adapters/mission/MissionHandler.kt [hunk 6]
```diff
@@ -6,6 +6,8 @@ import com.MAVLink.enums.MISSION_STATE
 import io.getstream.log.taggedLogger
 import kotlinx.coroutines.CoroutineScope
 import kotlinx.coroutines.launch
+import org.WenuLink.adapters.AsyncUtils
+import org.WenuLink.adapters.aircraft.ControlAuthority
```
Comment (TimonSchreiber) [inline app/src/main/java/org/WenuLink/adapters/mission/MissionHandler.kt]:
```suggestion
```

**Review by TimonSchreiber — CHANGES_REQUESTED** [review]
This looks mostly good to me, just a few small suggestions

---

I just notice that in `NavigationController.processDoReposition` the order of calling `dispatchCommand` and sending the `msgCommandAck` switched, is that intentional? Shouldn't the `MAV_RESULT.MAV_RESULT_ACCEPTED` only be send after the dispatch is successfull?

**Comment by angel-ayala** [comment]
Good that you mention it. I actually did that intentionally to prevent on sending `MAV_RESULT.MAV_RESULT_ACCEPTED` with too much delay after dispatch has a return in all the cases, nevertheless now I see that calling after or before the dispatch is kind of the same, unless move it inside the dispatch run block, in that case will only answering after success or error case.
I has been thinking in start using `[MAV_RESULT_IN_PROGRESS](https://mavlink.io/en/messages/common.html#MAV_RESULT_IN_PROGRESS)` to ensure an initial result value and then send it full progress or rejected on the dispatch. Also this probably will help to sync the QGC UI, because there are certain options made available when commands answer with ACCEPTED and still does reach a desired state.

If you agree I can add test such changes too to have a more robust mission microservice.

**Comment by TimonSchreiber** [comment]
I totaly agree with you!
I found that `CameraController.handleSetCameraMode` already uses a `MAV_RESULT_IN_PROGRESS` first and the `MAV_RESULT_ACCEPTED/REJECTED` only in the `dispatchCommand`s result lambda approach.

File: app/src/main/java/org/WenuLink/adapters/RequestCommand.kt (hunk 2 above)
Comment (angel-ayala) [reply app/src/main/java/org/WenuLink/adapters/RequestCommand.kt:132]: I put an excessive time because triggering a mission start only happens after reaching the initial altitude, and time could vary with slower speeds, maybe I could add a previous validation if is flying to first check if was able to arm and takeoff, before wait altitude.

**Review by TimonSchreiber — APPROVED** [review]
Lgtm
